src/bank/urls.py
from .views import create_bank, bank_list, bank_detail, cash_transfer,bank_to_excel_view, fetch_gcom_clients
from .views import update_payments, payment_reversal as reverse_payment, previous_years_banks, bank_list_asset, create_bank_asset

from django.urls import path

urlpatterns = [
    path('create/', create_bank, name='create_bank'),
    path('create-asset/', create_bank_asset, name='create_bank_asset'),
    path('list/', bank_list, name='bank_list'),
    path('list-assets/', bank_list_asset, name='bank_list_asset'),
    path('detail/<int:pk>/', bank_detail, name='bank_detail'),
    path('update/<int:pk>/', create_bank, name='update_bank'),
    path('transfer/', cash_transfer, name='cash_transfer'),
    path('excel/<int:pk>/', bank_to_excel_view, name='bank_to_excel'),
    path('update-payments/', update_payments, name='update_payments'),
    path('reverse-payment/', reverse_payment, name='reverse_payment'),
    path('previous-years/', previous_years_banks, name='previous_years_banks'),
    path('fetch-gcom-clients/', fetch_gcom_clients, name='fetch_gcom_clients'),
]

src/client/urls.py
from .views import create_client, edit_client, list_clients, individual_report, generate_client_id_view, create_prospect, view_prospects, edit_prospect

from django.urls import path

urlpatterns = [
    path('create/', create_client, name='create_client'),
    path('edit/<int:client_id>/', edit_client, name='edit_client'),
    path('list/', list_clients, name='list_clients'),
    path('individual-report/<int:pk>/', individual_report, name='individual_report'),
    path('generate-client-id/', generate_client_id_view, name='generate_client_id'),
    path('create-prospect/', create_prospect, name='create_prospect'),
    path('edit-prospect/<int:prospect_id>/', edit_prospect, name='edit_prospect'),
    path('prospects-list/', view_prospects, name='prospects_list'),
]

src/phoenix/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import include, path
from django.views.generic import RedirectView
from django.conf.urls import handler500
from django.http import HttpResponseServerError

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/accounts/login/')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('loan/', include('loan.urls')),
    path('client/', include('client.urls')),
    path('reports/', include('reports.urls')),
    path('bank/', include('bank.urls')),
    path('main/', include('main.urls')),
    path('savings/', include('savings.urls')),
    path('income/', include('income.urls')),
    path('expense/', include('expenses.urls')),
    path('asset/', include('asset.urls')),
    path('liability/', include('liability.urls')),
    path('user/', include('user.urls')),
    path('administration/', include('administration.urls')),
]

def custom_error_view(request, exception=None):
    return render(request, 'error.html', {'exception': str(exception)})

handler500 = custom_error_view

src/client/models.py
from datetime import datetime, date
from functools import cached_property
from django.db import models, IntegrityError
from django.apps import apps
from django.db import transaction
from administration.models import Tickets
from administration.manager import OfficeScopedManager
from user.models import User

class Client(models.Model):
    ACTIVE = 'A'
    LAPSE = 'L'
    DORMANT = 'D'
    PROSPECT = 'P'
    ACCOUNT_STATUS_CHOICES = [
        (ACTIVE, 'Active'),
        (LAPSE, 'Lapse'),
        (DORMANT, 'Dormant'),
        (PROSPECT, 'Prospect'),
    ]
    CLIENT_TYPE_CHOICES = [
        ('WL', 'Weekly Loan'),
        ('ML', 'Monthly Loan'),
        ('DC', 'Daily Contribution'),
        ('PR', 'Prospect'),
    ]

    client_id = models.CharField(max_length=100, unique=True, db_index=True, default=None, blank=True, null=True)
    name = models.CharField(max_length=100)
    email = models.EmailField(null=True, blank=True)
    phone = models.CharField(max_length=15)
    address = models.TextField(null=True, blank=True)
    marital_status = models.CharField(max_length=20, null=True, blank=True)
    next_of_kin = models.CharField(max_length=100, null=True, blank=True)
    next_of_kin_phone = models.CharField(max_length=15, null=True, blank=True)
    group = models.ForeignKey('main.ClientGroup', on_delete=models.CASCADE)
    bank_name = models.CharField(max_length=100, null=True, blank=True)
    account_number = models.CharField(max_length=100, null=True, blank=True)
    date = models.DateField(default=datetime.now)
    client_type = models.CharField(max_length=2, choices=CLIENT_TYPE_CHOICES, default='WL')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    account_status = models.CharField(
        max_length=1, choices=ACCOUNT_STATUS_CHOICES, default=ACTIVE
    )
    office = models.ForeignKey(
        'administration.Office', on_delete=models.CASCADE, null=True, blank=True, related_name='clients'
    )

    objects = OfficeScopedManager()

    def __str__(self):
        return f"{self.name}-{self.client_id}"

    @cached_property
    def savings(self):
        if self.group.name == 'Ajo':
            return self.savings_set.filter(type='D').first()
        return self.savings_set.first()

    @cached_property
    def loan(self):
        return self.loans.first()

    def save(self, *args, **kwargs):
        if not self.client_id:
            self.client_id = generate_client_id(self.client_type)
        elif self.client_id.startswith('PR') and self.client_type != 'PR':
            self.client_id = generate_client_id(self.client_type)
            self.account_status = Client.ACTIVE  # Set status to "Active" when client is activated
            self.client_type = self.client_type
            
            self.prospect.is_activated = True
            self.prospect.save()
        
        while True:
            try:
                with transaction.atomic():
                    super(Client, self).save(*args, **kwargs)
                break
            except IntegrityError:
                self.client_id = generate_client_id(self.client_type)

    def update_account_status(self):
        """
        Update the client's account status based on their loan activity.
        - Active: New loan after previous closed loan or less than 30 days of inactivity.
        - Lapse: Inactive for 30+ days with loan balance zero.
        - Dormant: Inactive for 60+ days.
        """
        last_payment = self.loans.filter(payment__isnull=False).order_by('-payment__payment_date').first()
        if not last_payment:
            new_status = Client.ACTIVE
        else:
            last_payment_date = last_payment.payment.order_by('-payment_date').first().payment_date
            days_since_last_payment = (date.today() - last_payment_date).days
    
            if days_since_last_payment >= 60:
                new_status = Client.DORMANT
                new_status_description = 'Dormant'
            elif days_since_last_payment >= 30:
                new_status = Client.LAPSE
                new_status_description = 'Lapse'
            else:
                new_status = Client.ACTIVE
                new_status_description = 'Active'
    
        if new_status != self.account_status:
            old_status = self.account_status
            old_status_description = dict(Client.ACCOUNT_STATUS_CHOICES)[old_status]

            self.account_status = new_status
            self.save(update_fields=['account_status'])
    
            if new_status in [Client.LAPSE, Client.DORMANT]:
                ticket = Tickets.objects.create(
                    client=self,
                    title=f"Account status changed to {new_status_description} for {self.name}",
                    description=(
                        f"Client {self.name} has been inactive for "
                        f"{days_since_last_payment if last_payment else 'N/A'} days. "
                        f"Status updated from {old_status_description} to {new_status_description}."
                    ),
                    priority='n',
                    closed=False,
                    created_by=User.objects.filter(is_superuser=True).first()
                )
                ticket.users.set(User.objects.all())
                ticket.save()


class Prospect(models.Model):
    LOAN_CHOICES = [
        ('WL', 'Weekly Loan'),
        ('ML', 'Monthly Loan'),
        ('BL', 'Business Loan'),
    ]
    client = models.OneToOneField(Client, on_delete=models.CASCADE, related_name='prospect')
    loan_amount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    loan_type = models.CharField(max_length=100, null=True, blank=True)
    date = models.DateField(default=datetime.now)
    is_activated = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Prospect: {self.client.name}"

def generate_client_id(client_type):
    """Generate a unique client ID based on the client type."""
    prefix = {
        'WL': 'WL',
        'ML': 'ML',
        'DC': 'DC',
        'PR': 'PR',
    }.get(client_type, 'CLI')

    last_client = Client.objects.filter(client_type=client_type, client_id__startswith=prefix).order_by('client_id').last()
    if not last_client:
        return f'{prefix}0001'
    
    try:
        last_id = int(last_client.client_id[len(prefix):])
    except ValueError:
        last_id = 0
    
    new_id = last_id + 1
    return f'{prefix}{new_id:04d}'

src/client/forms.py
from datetime import datetime
from django import forms

from main.models import ClientGroup, Year
from .models import Client, Prospect
from income.models import RegistrationFee, IDFee
from savings.models import CompulsorySavings
from bank.models import Bank



class ClientForm(forms.ModelForm):
    year = Year.current_year()
    compulsory_savings = forms.DecimalField(
        label='Compulsory Savings',
        required=False
    )
    registration_fee = forms.DecimalField(
        label='Registration Fee',
        required=False
    )
    id_fee = forms.DecimalField(
        label='ID Fee',
        required=False
    )
    bank = forms.ModelChoiceField(queryset=Bank.objects.filter(year=year), label='Bank')

    date = forms.DateField(
        label='Date',
        widget=forms.DateInput(attrs={'type': 'date'})
    )
    
    class Meta:
        model = Client
        fields = ['name', 'client_type', 'email', 'phone', 'address', 'group', 'marital_status', 'next_of_kin', 'next_of_kin_phone', 'bank_name', 'account_number', 'date']

    def __init__(self, *args, **kwargs):
        super(ClientForm, self).__init__(*args, **kwargs)
        self.fields['compulsory_savings'].initial = CompulsorySavings.objects.all().first().amount
        self.fields['registration_fee'].initial = RegistrationFee.objects.all().first().amount
        self.fields['id_fee'].initial = IDFee.objects.all().first().amount
        self.fields['date'].initial = datetime.now().date()

class ProspectForm(forms.ModelForm):
    date = forms.DateField(
        label='Date',
        widget=forms.DateInput(attrs={'type': 'date'}),
        initial=datetime.now().date()
    )
    loan_amount = forms.DecimalField(
        label='Loan Amount',
        required=False
    )
    loan_type = forms.ChoiceField(
        label='Loan Type',
        choices=[
            ('WL', 'Weekly Loan'),
            ('ML', 'Monthly Loan'),
            ('BL', 'Business Loan'),
        ],
        required=False
    )

    class Meta:
        model = Client
        fields = ['name', 'phone', 'date']

    def save(self, user, commit = True):
        # Add the prospect to the "Prospect" group
        instance = super().save(commit=False)
        prospect_group, _ = ClientGroup.objects.get_or_create(name='Prospect')
        instance.group = prospect_group
        instance.client_type = 'PR'
        instance.account_status = Client.PROSPECT  # Set status to "Prospect"
        instance.created_at = datetime.now()
        instance.updated_at = datetime.now()

        if commit:
            instance.save()
            Prospect.objects.create(
                client=instance,
                loan_amount=self.cleaned_data['loan_amount'],
                loan_type=self.cleaned_data['loan_type'],
                created_by=user
            )
        return instance

src/client/templates/client_excel_form.html
{% extends 'base.html' %}

{% load custom_filters %}

{% block title %}Client Form{% endblock %}

{% block content %}
        <h1>{{ form.instance.id|yesno:"Edit Client,Create Client" }}</h1>

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
{% endblock %}

src/client/templates/client_form.html
{% extends 'base_form.html' %} {% load custom_filters %} {% block title %}Create
New Customer{% endblock %} {% block form_content %}
<h1>{{ form.instance.id|yesno:"Edit Client,Create New Customer" }}</h1>

<form method="POST">
  {% csrf_token %}
  <div class="mb-3 col-md-6">
    <label for="id_client_id">Client ID</label>
    <input
      type="text"
      id="id_client_id"
      name="client_id"
      readonly
      class="form-control"
    />
  </div>
  {% csrf_token %} {{ form.as_p }}
  <button type="submit" class="btn btn-primary">
    {{ form.instance.id|yesno:"Update,Create" }}
  </button>
</form>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  $(document).ready(function () {
    $("#id_client_type").change(function () {
      var clientType = $(this).val();
      $.ajax({
        url: '{% url "generate_client_id" %}',
        data: {
          client_type: clientType,
        },
        success: function (data) {
          $("#id_client_id").val(data.client_id);
        },
      });
    });
  });
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
{% endblock %}

src/client/templates/client_list.html
{% extends 'base.html' %}

{% load custom_filters %}

{% block title %}Client List{% endblock %}

{% block content %}

    <h2 class="text-center">Clients List</h2>

    <!-- Search Form -->
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <form method="GET" action="{% url 'list_clients' %}" class="mb-4">
                    <div class="input-group mb-3">
                        <input type="text" name="q" class="form-control" placeholder="Search by name or client ID" >
                        <button class="btn btn-primary" type="submit">Search</button>
                    </div>
                </form>
            </div>
        </div>
    </div>


    <table class="table table-striped mt-4">
        <a href="{% url 'client_list_excel' %}" class="btn btn-primary">Download Excel</a>
        <thead>
            <tr>
                <th>Client ID</th>
                <th>Name</th>
                <th>Status</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Group</th>
                <th>Savings</th>
                <th>Loan</th>
            </tr>
        </thead>
        <tbody>
            {% for client in clients %}
            <tr>
                <td>{{ client.client_id }}</td>
                <td>
                    <a href="{% url 'individual_report' client.id %}">{{ client.name }}</a>
                </td>
                <td>{{ client.get_account_status_display }}</td>
                <td>{{ client.email }}</td>
                <td>{{ client.phone }}</td>
                <td>{{ client.group }}</td>
                <td>
                    {% if client.savings %}
                        <a href="{% url 'savings_detail' client.id %}">
                            {{ client.savings.balance|naira }}
                        </a>
                    {% else %}
                        N/A
                    {% endif %}
                </td>
                <td>
                    {% if client.loan %}
                        <a href="{% url 'loan_detail' client.loan.id %}">
                            {{ client.loan.balance|naira }}
                        </a>
                    {% else %}
                        N/A
                    {% endif %}
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="7" class="text-center">No clients found.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <!-- Pagination Controls -->
    <nav aria-label="Page navigation" class="pagination-bottom">
        <ul class="pagination justify-content-center">
            {% if clients.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1{% if query %}&q={{ query }}{% endif %}" aria-label="First">
                        <span aria-hidden="true">&laquo;&laquo;</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ clients.previous_page_number }}{% if query %}&q={{ query }}{% endif %}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" aria-label="First">
                        <span aria-hidden="true">&laquo;&laquo;</span>
                    </a>
                </li>
                <li class="page-item disabled">
                    <a class="page-link" href="#" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% endif %}
    
            <!-- Display page numbers -->
            {% for num in clients.paginator.page_range %}
                {% if clients.number == num %}
                    <li class="page-item active">
                        <a class="page-link" href="?page={{ num }}{% if query %}&q={{ query }}{% endif %}">{{ num }}</a>
                    </li>
                {% elif num > clients.number|add:'-3' and num < clients.number|add:'3' %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ num }}{% if query %}&q={{ query }}{% endif %}">{{ num }}</a>
                    </li>
                {% endif %}
            {% endfor %}
    
            {% if clients.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ clients.next_page_number }}{% if query %}&q={{ query }}{% endif %}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ clients.paginator.num_pages }}{% if query %}&q={{ query }}{% endif %}" aria-label="Last">
                        <span aria-hidden="true">&raquo;&raquo;</span>
                    </a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                <li class="page-item disabled">
                    <a class="page-link" href="#" aria-label="Last">
                        <span aria-hidden="true">&raquo;&raquo;</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
    <a href="{% url 'create_client' %}" class="btn btn-primary">Create New Client</a>
{% endblock %}

src/client/templates/prospect_form.html
{% extends 'base_form.html' %}

{% block title %}Add Prospect{% endblock %}

{% block form_content %}
<h1>Add Prospect</h1>

<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-primary">Add Prospect</button>
</form>
{% endblock %}

src/client/templates/prospect_list.html
{% extends 'base.html' %}

{% block title %}Prospect List{% endblock %}

{% block content %}
<h1>Prospect List</h1>

<table class="table table-striped">
    <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Phone</th>
            <th>Loan Amount</th>
            <th>Date</th>
            <th>Created By</th>
            <th>Actions</th>

        </tr>
    </thead>
    <tbody>
        {% for prospect in prospects %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ prospect.client.name }}</td>
            <td>{{ prospect.client.phone }}</td>
            <td>{{ prospect.loan_amount }}</td>
            <td>{{ prospect.date }}</td>
            <td>
                {{ prospect.created_by }}
            <td>
                <a href="{% url 'edit_prospect' prospect.client.id %}">Process</a>
        </tr>
        {% empty %}
        <tr>
            <td colspan="5">No prospects found.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<!-- Pagination -->
<div class="pagination">
    <span class="step-links">
        {% if prospects.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ prospects.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ prospects.number }} of {{ prospects.paginator.num_pages }}.
        </span>

        {% if prospects.has_next %}
            <a href="?page={{ prospects.next_page_number }}">next</a>
            <a href="?page={{ prospects.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}