src/bank/urls.py
from .views import create_bank, bank_list, bank_detail, cash_transfer,bank_to_excel_view, fetch_gcom_clients
from .views import update_payments, payment_reversal as reverse_payment, previous_years_banks, bank_list_asset, create_bank_asset

from django.urls import path

urlpatterns = [
    path('create/', create_bank, name='create_bank'),
    path('create-asset/', create_bank_asset, name='create_bank_asset'),
    path('list/', bank_list, name='bank_list'),
    path('list-assets/', bank_list_asset, name='bank_list_asset'),
    path('detail/<int:pk>/', bank_detail, name='bank_detail'),
    path('update/<int:pk>/', create_bank, name='update_bank'),
    path('transfer/', cash_transfer, name='cash_transfer'),
    path('excel/<int:pk>/', bank_to_excel_view, name='bank_to_excel'),
    path('update-payments/', update_payments, name='update_payments'),
    path('reverse-payment/', reverse_payment, name='reverse_payment'),
    path('previous-years/', previous_years_banks, name='previous_years_banks'),
    path('fetch-gcom-clients/', fetch_gcom_clients, name='fetch_gcom_clients'),
]

src/phoenix/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import include, path
from django.views.generic import RedirectView
from django.conf.urls import handler500
from django.http import HttpResponseServerError

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/accounts/login/')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('loan/', include('loan.urls')),
    path('client/', include('client.urls')),
    path('reports/', include('reports.urls')),
    path('bank/', include('bank.urls')),
    path('main/', include('main.urls')),
    path('savings/', include('savings.urls')),
    path('income/', include('income.urls')),
    path('expense/', include('expenses.urls')),
    path('asset/', include('asset.urls')),
    path('liability/', include('liability.urls')),
    path('user/', include('user.urls')),
    path('administration/', include('administration.urls')),
]

def custom_error_view(request, exception=None):
    return render(request, 'error.html', {'exception': str(exception)})

handler500 = custom_error_view

src/bank/models.py
from decimal import Decimal
from django.db import models
from django.utils import timezone

from user.models import User
from main.models import Year
from administration.manager import OfficeScopedManager


def recalculate_balance_after_payment_date(bank_id, payment_date):
    payments = BankPayment.objects.filter(bank_id=bank_id, payment_date__gt=payment_date).order_by('payment_date', 'created_at')
    bank = Bank.objects.get(id=bank_id)
    
    last_payment = BankPayment.objects.filter(bank_id=bank_id, payment_date__lte=payment_date).order_by('-payment_date', '-created_at').first()
    previous_balance = last_payment.bank_balance if last_payment else bank.balance_bf

    updates = []
    for payment in payments:
        payment.bank_balance = previous_balance + payment.amount
        previous_balance = payment.bank_balance
        updates.append(payment)

    BankPayment.objects.bulk_update(updates, ['bank_balance'])
        
class Bank(models.Model):
    BANK = 'B'
    ASSET = 'A'
    BANK_TYPE_CHOICES = [
        (BANK, 'Bank'),
        (ASSET, 'Asset'),
    ]
    name = models.CharField(max_length=100)
    description = models.TextField()
    type = models.CharField(max_length=50, choices=BANK_TYPE_CHOICES, default=BANK)
    balance = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    balance_bf = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    year = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='bank')
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='banks', null=True, blank=True)
    office = models.ForeignKey('administration.Office', on_delete=models.CASCADE, null=True, blank=True, related_name='banks')

    objects = OfficeScopedManager()

    def save(self, *args, **kwargs):
        if not self.year:
            self.year = Year.current_year() or 0
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.name} - {self.balance}'
    
    def record_payment(self, amount, description,payment_date,transaction):
        payment = BankPayment(bank=self, amount=amount,description=description, payment_date=payment_date,transaction=transaction)
        payment.save()
    class Meta:
        ordering = ['created_at']
        unique_together = ['name', 'year']

class BankPayment(models.Model):
    bank = models.ForeignKey(Bank, on_delete=models.CASCADE, related_name='payments', db_index=True)
    description = models.TextField()
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    bank_balance = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    transaction = models.ForeignKey('administration.Transaction', on_delete=models.CASCADE, null=True, blank=True, db_index=True, related_name='bank_payments')
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='bank_payments', null=True, blank=True)
    payment_date = models.DateField()

    def __str__(self):
        return f'{self.bank.name} - {self.description} - {self.amount}'
    
    def save(self, *args, **kwargs):
        if not self.pk:
            # Find the last transaction before the payment date
            last_payment = BankPayment.objects.filter(bank=self.bank, payment_date__lt=self.payment_date).order_by('-payment_date', '-created_at').first()
            if last_payment:
                self.bank_balance = last_payment.bank_balance + self.amount
            else:
                self.bank_balance = self.amount  # If no previous payment, start with the amount

            self.bank.balance += self.amount
            self.bank.save()
        
        super(BankPayment, self).save(*args, **kwargs)

        payment_date = self.payment_date - timezone.timedelta(days=1)
        recalculate_balance_after_payment_date(self.bank.id, payment_date)

    def delete(self, *args, **kwargs):
        # Adjust the bank's balance
        self.bank.balance -= self.amount
        self.bank.save()
    
        # Call the recalculation function for subsequent payments
        payment_date = self.payment_date - timezone.timedelta(days=1)
        recalculate_balance_after_payment_date(self.bank.id, payment_date)
    
        # Proceed with the deletion
        super(BankPayment, self).delete(*args, **kwargs)
    
    class Meta:
        ordering = ['payment_date', 'created_at']
        indexes = [
            models.Index(fields=['bank', 'payment_date', 'transaction'], name='idx_bank_payment_transaction'),
            models.Index(fields=['payment_date'], name='idx_payment_date'),
            models.Index(fields=['payment_date', 'created_at'], name='idx_payment_date_created_at'),
            models.Index(fields=['created_by'], name='idx_created_by'),
        ]


class PendingCashTransfer(models.Model):
    source_bank = models.ForeignKey(Bank, related_name='source_transfers', on_delete=models.CASCADE)
    destination_bank = models.ForeignKey(Bank, related_name='destination_transfers', on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    payment_date = models.DateField()
    transaction = models.OneToOneField('administration.Transaction', on_delete=models.CASCADE, null=True, blank=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    approved = models.BooleanField(default=False)
    approved_by = models.ForeignKey(User, related_name='approved_transfers', on_delete=models.CASCADE, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Transfer from {self.source_bank} to {self.destination_bank} - {self.amount}"

src/bank/forms.py
from django.forms import ModelForm
from django import forms

from administration.utils import validate_month_status
from main.models import Year
from .models import Bank, BankPayment



class BankForm(ModelForm):
    class Meta:
        model = Bank
        fields = ['name','description','balance_bf', 'user', 'type', 'office']


class CashTransferForm(forms.Form):

    year = Year.current_year()
    source_bank = forms.ModelChoiceField(queryset=Bank.objects.filter(year=year), label="Source Bank")
    destination_bank = forms.ModelChoiceField(queryset=Bank.objects.filter(year=year), label="Destination Bank")
    amount = forms.DecimalField(max_digits=10, decimal_places=2)
    description = forms.CharField(widget=forms.Textarea, required=False)
    payment_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))


class DateRangeForm(forms.Form):
    start_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    end_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))



class ReversePaymentForm(forms.Form):
    year = Year.current_year()
    type = forms.ChoiceField(choices=(('SVS','Savings'), ('LOA','Loan'), ('COM','Combined'), ('GCOM','Group Combined')), label='Type')
    bank = forms.ModelChoiceField(queryset=Bank.objects.filter(year=year), label='Bank')
    payment_date = forms.DateField(widget=forms.SelectDateWidget(years=range(2000, 2030)))
    payment = forms.ModelChoiceField(queryset=BankPayment.objects.none())
    reversal_date = forms.DateField(widget=forms.SelectDateWidget(years=range(2000, 2030)))
    reason = forms.CharField(widget=forms.Textarea, required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['payment'].queryset = BankPayment.objects.none()
        if 'type' in self.data and 'bank' in self.data and 'payment_date_day' in self.data:
            try:
                type = self.data.get('type')
                bank_id = int(self.data.get('bank'))
                payment_date_day = self.data.get('payment_date_day')
                payment_date_month = self.data.get('payment_date_month')
                payment_date_year = self.data.get('payment_date_year')
                payment_date = f'{payment_date_year}-{payment_date_month}-{payment_date_day}'
                self.fields['payment'].queryset = self.get_filtered_payments(type, bank_id, payment_date)
            except (ValueError, TypeError):
                pass
        else:
            self.fields['payment'].queryset = BankPayment.objects.none()

    def get_filtered_payments(self, type, bank_id, payment_date):
        return BankPayment.objects.filter(
            bank=bank_id,
            payment_date=payment_date,
            transaction__reference_number__startswith=type[:3]
        )
    

src/bank/templates/bank_detail.html
{% extends 'base.html' %}

{% load custom_filters %}

{% block title %}Bank Detail{% endblock %}

{% block content %}
    <h1 class="text-center mb-4">Bank Detail</h1>
    <a href="{% url 'bank_to_excel' bank.id %}" class="btn btn-primary">Download Excel</a>
    <div class="card">
        <div class="card-header">
            <h2>{{ bank.name }}</h2>
        </div>
        <div class="card-body">
            <p><strong>Description:</strong> {{ bank.description }}</p>
            <p><strong>Balance:</strong> {{ bank.balance }}</p>
            <p><strong>Balance BF:</strong> {{ bank.balance_bf }}</p>
            <p><strong>Year:</strong> {{ bank.year }}</p>
            <p><strong>Created At:</strong> {{ bank.created_at }}</p>
        </div>
    </div>

    <!-- Date Range Form -->
    <div class="mt-4">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Filter</button>
        </form>
    </div>

    <!-- Bank Payments Section -->
    <div class="mt-5">
        <h3>Bank Payments</h3>
        {% if bank_payment %}
            <table class="table-report">
                <thead class="table-dark">
                    <tr>
                        <th>#</th>
                        <th>Date</th>
                        <th>id</th>
                        <th>Ref No</th>
                        <th>Description</th>
                        <th>Amount</th>
                        <th>Balance</th>
                        {% if user.is_superuser %}
                        <th>Created At</th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for payment in bank_payment %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ payment.payment_date }}</td>
                        <td>{{ payment.id }}</td>
                        <td>{{ payment.transaction.reference_number }}</td>
                        <td>{{ payment.description }}</td>
                        <td>{{ payment.amount|naira }}</td>
                        <td>{{ payment.bank_balance|naira }}</td>
                        {% if user.is_superuser %}
                        <td>{{ payment.created_at }}</td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                    
                </tbody>
            </table>
        {% else %}
            <p>No payments found for this bank.</p>
        {% endif %}
    </div>

    <div class="mt-4">
        <a href="{% url 'bank_list' %}" class="btn btn-primary">Back to Bank List</a>
    </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
{% endblock %}

src/bank/templates/bank_list.html
{% extends 'base.html' %}

{% load custom_filters %}

{% block title %}Bank List{% endblock %}

{% block content %}
    <h1 class="text-center mb-4">Bank List - {{ current_year }}</h1>
    <div class="text-end mb-3">
        {% if has_previous_years_banks %}
            <a href="{% url 'previous_years_banks' %}" class="btn btn-primary">View Previous Years</a>
        {% endif %}
    </div>
    <table class="table-report">
        <thead class="table-dark">
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Description</th>
                <th>Balance</th>
                <th>Year</th>
            </tr>
        </thead>
        <tbody>
            {% for bank in banks %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                    <a href="{% url 'bank_detail' bank.id %}">{{ bank.name }}</a>
                </td>
                <td>{{ bank.description }}</td>
                <td>{{ bank.balance }}</td>
                <td>{{ bank.year }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

src/bank/templates/cash_transfer.html
{% extends 'base_form.html' %}

{% load custom_filters %}

{% block title %}Cash Transfer{% endblock %}

{% block form_content %}
        <h1 class="text-center mb-4">Cash Transfer</h1>
        <form method="post">
            {% csrf_token %}
            {% if form.non_field_errors %}
            <div class="error">
                {{ form.non_field_errors }}
            </div>
            {% endif %}
            <div class="mb-3">
                {{ form.source_bank.label_tag }}<br>
                {{ form.source_bank }}
            </div>
            <div class="mb-3">
                {{ form.destination_bank.label_tag }}<br>
                {{ form.destination_bank }}
            </div>
            <div class="mb-3">
                {{ form.amount.label_tag }}<br>
                {{ form.amount }}
            </div>
            <div class="mb-3">
                {{ form.description.label_tag }}<br>
                {{ form.description }}
            </div>
            <div class="mb-3">
                {{ form.payment_date.label_tag }}<br>
                {{ form.payment_date }}
            </div>
            <button type="submit" class="btn btn-primary">Transfer</button>
        </form>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
{% endblock %}

src/bank/templates/create_bank.html
{% extends 'base_form.html' %}

{% load custom_filters %}

{% block title %}Create Bank{% endblock %}

{% block form_content %}
        <h1>Create Bank</h1>

        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
{% endblock %}

src/bank/templates/payment_reversal.html
{% extends 'base_form.html' %}

{% load custom_filters %}

{% block title %}Reverse Payment{% endblock %}

{% block form_content %}
        <h1>Reverse Payment</h1>

        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
    $(document).ready(function() {
        function updatePayments() {
            var type = $('#id_type').val();
            var bank = $('#id_bank').val();
            var payment_date = $('#id_payment_date_year').val() + '-' + $('#id_payment_date_month').val() + '-' + $('#id_payment_date_day').val();
    
            if (type && bank && payment_date) {
                $.ajax({
                    url: '{% url "update_payments" %}',
                    data: {
                        'type': type,
                        'bank': bank,
                        'payment_date': payment_date
                    },
                    success: function(data) {
                        $('#id_payment').html(data);
                    }
                });
            }
        }
    
        $('#id_type, #id_bank, #id_payment_date_year, #id_payment_date_month, #id_payment_date_day').change(updatePayments);
    });
    </script>
{% endblock %}

src/bank/templates/payments_dropdown_list_options.html
{% for payment in payments %}
<option value="{{ payment.id }}">{{ payment }}</option>
{% endfor %}